version: "3.7"

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  vault:
    image: vault:1.6.3 # Zmiana na konkretną wersję obrazu Vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data

  myapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse
      - vault

volumes:
  clickhouse_data:
  vault_data:
